### ISSUE TITLE
404 from crates.io

### ISSUE THREAD

**Issue by pravic** [g-k/cargo-show#102]
It's been for a while:
```
$ cargo show bat --json
Error fetching data for bat: api errors (status 404 Not Found): Not Found
```

The culprit: 
`curl -ik https://crates.io//api/v1/crates/bat` vs 
`curl -ik https://crates.io/api/v1/crates/bat`.

Apparently, it is a bug in crates.io, but it's better to fix it here.

**Comment by g-k** [comment]
Good catch!
