### ISSUE TITLE
Output dependencies?

### ISSUE THREAD

**Issue by pravic** [g-k/cargo-show#14]
Sometimes I need to view dependencies of some crate and I think that it would be easier to add this feature (via a command line option) here rather than creating a separate tool for that.

What do you think?

**Comment by g-k** [comment]
I'm open to it.

Do you have an idea what the output might look like? Would we just fetch direct dependents (A > B) or indirect dependents (A > B > C) too? Something like [cargo-tree](https://github.com/sfackler/cargo-tree)?

**Comment by pravic** [comment]
Too noisy, imho. I'd prefer something similar to `cargo tree` (at least, in non-verbose mode).
