### ISSUE TITLE
Add @pravic as co-maintainer?

### ISSUE THREAD

**Issue by g-k** [g-k/cargo-show#22]
@pravic thanks for helping out recently, are you interested in getting write access to the repo and being credited as a maintainer?

If so, I'll make the changes:

* grant write access to the repo
* add a maintainers section to the readme

and expect the usual open source stuff from you (basically what you've been doing already):

* help with development, code review, and feedback on issues as your free time permits
* be nice to people

**Comment by pravic** [comment]
Yeah, I am okay with that. Thanks.
