### ISSUE TITLE
Please, update to newer cargo, dependencies no longer build

### ISSUE THREAD

**Issue by jan-hudec** [g-k/cargo-show#9]
The cargo version used depends on libgit2-sys v0.4.6, which no longer builds on Debian Testing. Since newer versions build just fine, the easiest fix would be to update to newer cargo.

The errors are:
```
libgit2-sys-0.4.6/libgit2/src/openssl_stream.c:146:3: error: dereferencing pointer to incomplete type ‘BIO {aka struct bio_st}’
libgit2-sys-0.4.6/libgit2/src/openssl_stream.c:204:1: error: variable ‘git_stream_bio_method’ has initializer but incomplete type
```

**Comment by g-k** [comment]
Updated! Can you try 0.3.0 and let me know if it fixes the problem?

Note: it builds for me on nightly (via git clone and `cargo build`), but `cargo --version` and `cargo install cargo-show` both panic which looks like a problem with rust or cargo nightly.

**Comment by jan-hudec** [comment]
Builds fine for me (I normally build everything with stable rust and use nightly only if necessary or for testing).

**Comment by g-k** [comment]
Great! Thanks for reporting the issue.
